export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const GET_FORECAST_WEATHER = "GET_FORECAST_WEATHER";
export const GET_AIR_POLLUTION = "GET_AIR_POLLUTION";
export const GET_CITY = "GET_CITY";