export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const GET_FORECAST_WEATHER = "GET_FORECAST_WEATHER";
export const GET_AIR_POLLUTION = "GET_AIR_POLLUTION";
export const GET_CITY = "GET_CITY";
export const GET_WEATHER_DETAILS = "GET_WEATHER_DETAILS";
export const SET_WEATHER_WEEK = "SET_WEATHER_WEEK";